//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGGOBEST.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Customers_ARGGOBE" +
            "ST")]
        public string ARGGOBEST_Customers_ARGGOBEST_Customers_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_Customers_ARGGOBEST_Customers_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Customers_ARGGOBE" +
            "ST")]
        public string ARGGOBEST_WebCustomers_Customers_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_WebCustomers_Customers_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Project_Users_ARG" +
            "GOBEST")]
        public string ARGGOBEST_consulting_arggo_nav2018_Project_Users_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_consulting_arggo_nav2018_Project_Users_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Projects_ARGGOBES" +
            "T")]
        public string ARGGOBEST_consulting_arggo_nav2018_Projects_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_consulting_arggo_nav2018_Projects_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Roles_ARGGOBEST")]
        public string ARGGOBEST_consulting_arggo_nav2018_Roles_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_consulting_arggo_nav2018_Roles_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Task_Logs_ARGGOBE" +
            "ST")]
        public string ARGGOBEST_Task_Logs_ARGGOBEST_Task_Logs_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_Task_Logs_ARGGOBEST_Task_Logs_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Task_Users_ARGGOB" +
            "EST")]
        public string ARGGOBEST_Task_Users_ARGGOBEST_Task_Users_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_Task_Users_ARGGOBEST_Task_Users_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Task_ARGGOBEST")]
        public string ARGGOBEST_Task_ARGGOBEST_Task_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_Task_ARGGOBEST_Task_ARGGOBEST_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus09/Page/Users_ARGGOBEST")]
        public string ARGGOBEST_Users_ARGGOBEST_Users_ARGGOBEST_Service {
            get {
                return ((string)(this["ARGGOBEST_Users_ARGGOBEST_Users_ARGGOBEST_Service"]));
            }
        }
    }
}
