//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ARGGOBEST.Task_ARGGOBEST {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Task_ARGGOBEST_Binding", Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public partial class Task_ARGGOBEST_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Task_ARGGOBEST_Service() {
            this.Url = global::ARGGOBEST.Properties.Settings.Default.ARGGOBEST_Task_ARGGOBEST_Task_ARGGOBEST_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Task_ARGGOBEST")]
        public Task_ARGGOBEST Read(int Task_ID) {
            object[] results = this.Invoke("Read", new object[] {
                        Task_ID});
            return ((Task_ARGGOBEST)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(int Task_ID) {
            this.ReadAsync(Task_ID, null);
        }
        
        /// <remarks/>
        public void ReadAsync(int Task_ID, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Task_ID}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Task_ARGGOBEST")]
        public Task_ARGGOBEST ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((Task_ARGGOBEST)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Task_ARGGOBEST[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] Task_ARGGOBEST_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((Task_ARGGOBEST[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Task_ARGGOBEST_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Task_ARGGOBEST_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref Task_ARGGOBEST Task_ARGGOBEST) {
            object[] results = this.Invoke("Create", new object[] {
                        Task_ARGGOBEST});
            Task_ARGGOBEST = ((Task_ARGGOBEST)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(Task_ARGGOBEST Task_ARGGOBEST) {
            this.CreateAsync(Task_ARGGOBEST, null);
        }
        
        /// <remarks/>
        public void CreateAsync(Task_ARGGOBEST Task_ARGGOBEST, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        Task_ARGGOBEST}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref Task_ARGGOBEST[] Task_ARGGOBEST_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        Task_ARGGOBEST_List});
            Task_ARGGOBEST_List = ((Task_ARGGOBEST[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(Task_ARGGOBEST[] Task_ARGGOBEST_List) {
            this.CreateMultipleAsync(Task_ARGGOBEST_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(Task_ARGGOBEST[] Task_ARGGOBEST_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        Task_ARGGOBEST_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref Task_ARGGOBEST Task_ARGGOBEST) {
            object[] results = this.Invoke("Update", new object[] {
                        Task_ARGGOBEST});
            Task_ARGGOBEST = ((Task_ARGGOBEST)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(Task_ARGGOBEST Task_ARGGOBEST) {
            this.UpdateAsync(Task_ARGGOBEST, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(Task_ARGGOBEST Task_ARGGOBEST, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        Task_ARGGOBEST}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref Task_ARGGOBEST[] Task_ARGGOBEST_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        Task_ARGGOBEST_List});
            Task_ARGGOBEST_List = ((Task_ARGGOBEST[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(Task_ARGGOBEST[] Task_ARGGOBEST_List) {
            this.UpdateMultipleAsync(Task_ARGGOBEST_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(Task_ARGGOBEST[] Task_ARGGOBEST_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        Task_ARGGOBEST_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/task_arggobest:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public partial class Task_ARGGOBEST {
        
        private string keyField;
        
        private int task_IDField;
        
        private bool task_IDFieldSpecified;
        
        private int project_IDField;
        
        private bool project_IDFieldSpecified;
        
        private string task_TitleField;
        
        private string task_DescriptionField;
        
        private Priority priorityField;
        
        private bool priorityFieldSpecified;
        
        private decimal estimated_Analysis_HoursField;
        
        private bool estimated_Analysis_HoursFieldSpecified;
        
        private decimal estimated_Design_HoursField;
        
        private bool estimated_Design_HoursFieldSpecified;
        
        private decimal estimated_Development_HoursField;
        
        private bool estimated_Development_HoursFieldSpecified;
        
        private decimal estimated_Testing_HoursField;
        
        private bool estimated_Testing_HoursFieldSpecified;
        
        private System.DateTime required_Due_DateField;
        
        private bool required_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Analysis_Due_DateField;
        
        private bool estimated_Analysis_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Design_Due_DateField;
        
        private bool estimated_Design_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Development_Due_DateField;
        
        private bool estimated_Development_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Testing_Due_DateField;
        
        private bool estimated_Testing_Due_DateFieldSpecified;
        
        private System.DateTime actual_Analysis_Due_DateField;
        
        private bool actual_Analysis_Due_DateFieldSpecified;
        
        private System.DateTime actual_Design_Due_DateField;
        
        private bool actual_Design_Due_DateFieldSpecified;
        
        private System.DateTime actual_Development_Due_DateField;
        
        private bool actual_Development_Due_DateFieldSpecified;
        
        private System.DateTime actual_Testing_Due_DateField;
        
        private bool actual_Testing_Due_DateFieldSpecified;
        
        private decimal actual_Analysis_HoursField;
        
        private bool actual_Analysis_HoursFieldSpecified;
        
        private decimal actual_Design_HoursField;
        
        private bool actual_Design_HoursFieldSpecified;
        
        private decimal actual_Development_HoursField;
        
        private bool actual_Development_HoursFieldSpecified;
        
        private decimal actual_Testing_HoursField;
        
        private bool actual_Testing_HoursFieldSpecified;
        
        private Initial_Task_Type initial_Task_TypeField;
        
        private bool initial_Task_TypeFieldSpecified;
        
        private Current_Task_Type current_Task_TypeField;
        
        private bool current_Task_TypeFieldSpecified;
        
        private string license_DetailsField;
        
        private int owner_User_IDField;
        
        private bool owner_User_IDFieldSpecified;
        
        private string task_ResolutionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public int Task_ID {
            get {
                return this.task_IDField;
            }
            set {
                this.task_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Task_IDSpecified {
            get {
                return this.task_IDFieldSpecified;
            }
            set {
                this.task_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Project_ID {
            get {
                return this.project_IDField;
            }
            set {
                this.project_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Project_IDSpecified {
            get {
                return this.project_IDFieldSpecified;
            }
            set {
                this.project_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Task_Title {
            get {
                return this.task_TitleField;
            }
            set {
                this.task_TitleField = value;
            }
        }
        
        /// <remarks/>
        public string Task_Description {
            get {
                return this.task_DescriptionField;
            }
            set {
                this.task_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Estimated_Analysis_Hours {
            get {
                return this.estimated_Analysis_HoursField;
            }
            set {
                this.estimated_Analysis_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Analysis_HoursSpecified {
            get {
                return this.estimated_Analysis_HoursFieldSpecified;
            }
            set {
                this.estimated_Analysis_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Estimated_Design_Hours {
            get {
                return this.estimated_Design_HoursField;
            }
            set {
                this.estimated_Design_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Design_HoursSpecified {
            get {
                return this.estimated_Design_HoursFieldSpecified;
            }
            set {
                this.estimated_Design_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Estimated_Development_Hours {
            get {
                return this.estimated_Development_HoursField;
            }
            set {
                this.estimated_Development_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Development_HoursSpecified {
            get {
                return this.estimated_Development_HoursFieldSpecified;
            }
            set {
                this.estimated_Development_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Estimated_Testing_Hours {
            get {
                return this.estimated_Testing_HoursField;
            }
            set {
                this.estimated_Testing_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Testing_HoursSpecified {
            get {
                return this.estimated_Testing_HoursFieldSpecified;
            }
            set {
                this.estimated_Testing_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Required_Due_Date {
            get {
                return this.required_Due_DateField;
            }
            set {
                this.required_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Required_Due_DateSpecified {
            get {
                return this.required_Due_DateFieldSpecified;
            }
            set {
                this.required_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Estimated_Analysis_Due_Date {
            get {
                return this.estimated_Analysis_Due_DateField;
            }
            set {
                this.estimated_Analysis_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Analysis_Due_DateSpecified {
            get {
                return this.estimated_Analysis_Due_DateFieldSpecified;
            }
            set {
                this.estimated_Analysis_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Estimated_Design_Due_Date {
            get {
                return this.estimated_Design_Due_DateField;
            }
            set {
                this.estimated_Design_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Design_Due_DateSpecified {
            get {
                return this.estimated_Design_Due_DateFieldSpecified;
            }
            set {
                this.estimated_Design_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Estimated_Development_Due_Date {
            get {
                return this.estimated_Development_Due_DateField;
            }
            set {
                this.estimated_Development_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Development_Due_DateSpecified {
            get {
                return this.estimated_Development_Due_DateFieldSpecified;
            }
            set {
                this.estimated_Development_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Estimated_Testing_Due_Date {
            get {
                return this.estimated_Testing_Due_DateField;
            }
            set {
                this.estimated_Testing_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Testing_Due_DateSpecified {
            get {
                return this.estimated_Testing_Due_DateFieldSpecified;
            }
            set {
                this.estimated_Testing_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Actual_Analysis_Due_Date {
            get {
                return this.actual_Analysis_Due_DateField;
            }
            set {
                this.actual_Analysis_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Analysis_Due_DateSpecified {
            get {
                return this.actual_Analysis_Due_DateFieldSpecified;
            }
            set {
                this.actual_Analysis_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Actual_Design_Due_Date {
            get {
                return this.actual_Design_Due_DateField;
            }
            set {
                this.actual_Design_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Design_Due_DateSpecified {
            get {
                return this.actual_Design_Due_DateFieldSpecified;
            }
            set {
                this.actual_Design_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Actual_Development_Due_Date {
            get {
                return this.actual_Development_Due_DateField;
            }
            set {
                this.actual_Development_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Development_Due_DateSpecified {
            get {
                return this.actual_Development_Due_DateFieldSpecified;
            }
            set {
                this.actual_Development_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Actual_Testing_Due_Date {
            get {
                return this.actual_Testing_Due_DateField;
            }
            set {
                this.actual_Testing_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Testing_Due_DateSpecified {
            get {
                return this.actual_Testing_Due_DateFieldSpecified;
            }
            set {
                this.actual_Testing_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Actual_Analysis_Hours {
            get {
                return this.actual_Analysis_HoursField;
            }
            set {
                this.actual_Analysis_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Analysis_HoursSpecified {
            get {
                return this.actual_Analysis_HoursFieldSpecified;
            }
            set {
                this.actual_Analysis_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Actual_Design_Hours {
            get {
                return this.actual_Design_HoursField;
            }
            set {
                this.actual_Design_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Design_HoursSpecified {
            get {
                return this.actual_Design_HoursFieldSpecified;
            }
            set {
                this.actual_Design_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Actual_Development_Hours {
            get {
                return this.actual_Development_HoursField;
            }
            set {
                this.actual_Development_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Development_HoursSpecified {
            get {
                return this.actual_Development_HoursFieldSpecified;
            }
            set {
                this.actual_Development_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Actual_Testing_Hours {
            get {
                return this.actual_Testing_HoursField;
            }
            set {
                this.actual_Testing_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Testing_HoursSpecified {
            get {
                return this.actual_Testing_HoursFieldSpecified;
            }
            set {
                this.actual_Testing_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Initial_Task_Type Initial_Task_Type {
            get {
                return this.initial_Task_TypeField;
            }
            set {
                this.initial_Task_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Initial_Task_TypeSpecified {
            get {
                return this.initial_Task_TypeFieldSpecified;
            }
            set {
                this.initial_Task_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Current_Task_Type Current_Task_Type {
            get {
                return this.current_Task_TypeField;
            }
            set {
                this.current_Task_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Current_Task_TypeSpecified {
            get {
                return this.current_Task_TypeFieldSpecified;
            }
            set {
                this.current_Task_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string License_Details {
            get {
                return this.license_DetailsField;
            }
            set {
                this.license_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public int Owner_User_ID {
            get {
                return this.owner_User_IDField;
            }
            set {
                this.owner_User_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Owner_User_IDSpecified {
            get {
                return this.owner_User_IDFieldSpecified;
            }
            set {
                this.owner_User_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Task_Resolution {
            get {
                return this.task_ResolutionField;
            }
            set {
                this.task_ResolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Priority {
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Initial_Task_Type {
        
        /// <remarks/>
        Bug,
        
        /// <remarks/>
        Change_Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Current_Task_Type {
        
        /// <remarks/>
        Bug,
        
        /// <remarks/>
        Change_Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public partial class Task_ARGGOBEST_Filter {
        
        private Task_ARGGOBEST_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public Task_ARGGOBEST_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Task_ARGGOBEST_Fields {
        
        /// <remarks/>
        Task_ID,
        
        /// <remarks/>
        Project_ID,
        
        /// <remarks/>
        Task_Title,
        
        /// <remarks/>
        Task_Description,
        
        /// <remarks/>
        Priority,
        
        /// <remarks/>
        Estimated_Analysis_Hours,
        
        /// <remarks/>
        Estimated_Design_Hours,
        
        /// <remarks/>
        Estimated_Development_Hours,
        
        /// <remarks/>
        Estimated_Testing_Hours,
        
        /// <remarks/>
        Required_Due_Date,
        
        /// <remarks/>
        Estimated_Analysis_Due_Date,
        
        /// <remarks/>
        Estimated_Design_Due_Date,
        
        /// <remarks/>
        Estimated_Development_Due_Date,
        
        /// <remarks/>
        Estimated_Testing_Due_Date,
        
        /// <remarks/>
        Actual_Analysis_Due_Date,
        
        /// <remarks/>
        Actual_Design_Due_Date,
        
        /// <remarks/>
        Actual_Development_Due_Date,
        
        /// <remarks/>
        Actual_Testing_Due_Date,
        
        /// <remarks/>
        Actual_Analysis_Hours,
        
        /// <remarks/>
        Actual_Design_Hours,
        
        /// <remarks/>
        Actual_Development_Hours,
        
        /// <remarks/>
        Actual_Testing_Hours,
        
        /// <remarks/>
        Initial_Task_Type,
        
        /// <remarks/>
        Current_Task_Type,
        
        /// <remarks/>
        License_Details,
        
        /// <remarks/>
        Owner_User_ID,
        
        /// <remarks/>
        Task_Resolution,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST Task_ARGGOBEST {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST[] Task_ARGGOBEST_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST Task_ARGGOBEST {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task_ARGGOBEST[] Task_ARGGOBEST_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task_ARGGOBEST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591